name: village
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  flutter_animate: ^4.5.2
  provider: ^6.1.1
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_storage: ^13.2.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  supabase_flutter: ^2.8.1
  google_maps_flutter: ^2.5.3
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/hero_village.jpg
    - assets/images/hero.png
    - assets/images/fair.png
    - assets/images/meeting.png
    - assets/images/master_education.png
    - assets/images/master_cleaning.png
    - assets/images/master_farming.png
